### 验证码
GET {{host}}/crap/auth/captcha?ticket=1

### 验证码 POST
POST {{host}}/crap/auth/captcha?ticket=1&width=420&height=250

> {%
    client.global.set("captcha", JSON.parse(response.body).data);
    client.log(JSON.parse(response.body).data);
%}


### 解析验证码
POST http://auto.sajor.work/login_base
Content-Type: application/json

{
  "base64": "{{captcha}}",
  "count": 1,
  "name": "erp",
  "threshold": 200
}

> {%
    client.global.set("code", response.body);
    client.log(response.body);
%}

### 用户登陆接口
POST {{host}}/crap/auth/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username=sys&password=sys&ticket=1&verify=6Zr2
# username=sys&password=sys&ticket=1&verify={code}

> {%
    client.global.set("auth_token", JSON.parse(response.body).data.token);
    client.log(JSON.parse(response.body).data.token);
%}

### 用户注销
POST {{host}}/crap/auth/logout
Authorization: Bearer {{auth_token}}

### 用户密码修改
POST {{host}}/route/crap/system/password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "sign": "",
  "timestamp": 1675765315417,
  "data": {
    "password": "sys",
    "new_password": "123"
  }
}

# ==========================================================================================

### 用户注册
POST {{host}}/route/crap/system/create-user
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "sign": "",
  "timestamp": 1675765315417,
  "data": {
    "name": "测试名称",
    "mobile": "13111122223",
    "username": "13111122223",
    "password": "9!0wT@4k",
    "department_ids": [
      "1350839640403349506",
      "1350839759722909697",
      "1350839956716785665"
    ],
    "remark": "测试名称的附属内容"
  }
}

