server:
  port: 2727                                      # 测试环境 : 端口号=8080+项目号, 比如项目号是10, 端口号=8090
  servlet:
    context-path: /api                            # ! 测试/生产环境替换
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  datasource:
    username: ENC(uUVVLhshTArj/Gd/AjpCIg==)
    password: ENC(PlN23RnLACpu7quB0QRlnA==)
    url: jdbc:mysql://localhost:3306/crap
    driver-class-name: com.mysql.cj.jdbc.Driver
  # * 允许循环引用
  main:
    allow-circular-references: true

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto

logging:
  level:
    work.sajor: debug
    org.*: warn
    com.*: warn
    org.springframework.data: error
    org.springframework.boot.autoconfigure.orm.jpa: error
    work.sajor.crap.server: info
    work.sajor.crap.core.security.component: info
    work.sajor.crap.core.security.jwt: info
  file:
    path: /tmp/crap/log

# * Mybatis Plus
mybatis-plus:
  mapper-locations: classpath*:work/sajor/**/*Mapper.xml
  typeAliasesPackage: work.sajor.**.entity
  typeEnumsPackage: work.sajor.**                  # enum 定义在实体扩展类内
  global-config:
    banner: false                                 # 关闭 MP3.0 自带的banner
    workerId: 1                                   # SnowFlake : 机器 ID
    datacenterId: 1                               # SnowFlake : 数据标识 ID
    db-config:
      id-type: ASSIGN_ID                          # 使用 SnowFlake. 主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      table-underline: true                       # 默认数据库表下划线命名
      logic-delete-field: delete_flag             # 全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: now()                   # 逻辑已删除值(默认为 1)
      logic-not-delete-value: "null"              # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: work.sajor.crap.core.mybatis.support.MybatisLogger
#    cache-enabled: false                          # 禁用二级缓存
#    local-cache-scope: statement                  # 禁用一级缓存

## Spring Boot 健康监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"                              # 开放全部端口  默认health，info
#      base-path: /actuator/monitor                # 自定义路径
#    enabled-by-default: true
#  endpoint:
#    health:
#      show-details: always                        # 展示应用信息详情数据
#  server:
#    port: ${server.port}                          # 监控端口


crap:
  id: ${hostname:localhost}                       # 节点标识
  cache-ttl: 600s                                 # 缓存时间
  debug-user: false                               # 允许切换用户

  # * 挂载目录
  path:
    tmp: /tmp/crap/tmp                           # 临时目录
    log: /tmp/crap/log                           # 日志目录
    source: /tmp/crap/source                     # 源码目录, public 为 web 根目录, public/upload 为上传目录

  # * 安全验证
  security:
    enable: true                                  # 是否开启
    verify-enable: false                          # 是否开启验证码功能
    role-permission-enable: true                  # 是否开启角色认证功能
    cross-origin: "*"                             # ! 生产环境限定 允许跨域的 Host, 多个用逗号分隔
    multi-session: true                           # ! 生产环境关闭 多客户端登录同一账号
    username-parameter: username                  # 用户名字段名称
    password-parameter: password                  # 密码字段名称
    dev-user: sys                                 # 开发者账号 $e0801$e9+PjBhhF823XuLiYZgajxJUMckW/Tq8AUkwAmFslGVMC74ALP3tJhWHu3yGsyXUPHW9qyTsldBNMHAhF56D9w==$L2v/Zwk7bVN+lJU0zLMol0OpsCU8Z1ZQQLT2EVSWH6w=
    anonymous-urls: # 不需要登录的地址
      - /open/**                                  # 开放接口
      - /actuator/**                              # 应用监控
    public-urls: # 不需要授权的地址, 登录即可访问
      - /crap/system/**                           # Crap 基础功能
    jwt: # Json Web Token
      secret: CRAP=JWT=SECRET=CRAP=JWT=SECRET=CRAP=JWT=SECRET=CRAP=JWT=SECRET                     # ! 生产环境替换 加密密钥
      expire: 3600                                # 过期时间(s), 3600 = 1 小时
      remember-me-expire: 2592000                 # 保持登录时间(s), 2592000 = 30 天
      refresh: 600                                # db 刷新间隔(s), 600 = 10 分钟

jasypt:
  encryptor:
    password: ${ENCRYPTOR_PASSWORD:b1ncjbS<AYq'/iH}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator